2019-11-22 13:56:46 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 13:56:47 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 13:56:51 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 13:56:51 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 13:56:52 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 13:56:53 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 13:56:56 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select this_.id as id1_7_0_, this_.version as version2_7_0_, this_.usuario_id as usuario_3_7_0_, this_.password_expired as password4_7_0_, this_.username as username5_7_0_, this_.account_locked as account_6_7_0_, this_."password" as password7_7_0_, this_.account_expired as account_8_7_0_, this_.enabled as enabled9_7_0_ from user this_ where this_.username=? [42102-196]
2019-11-22 13:56:57 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 13:56:57 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 13:57:04 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "USER" no encontrada
Table "USER" not found; SQL statement:
select this_.id as id1_7_0_, this_.version as version2_7_0_, this_.usuario_id as usuario_3_7_0_, this_.password_expired as password4_7_0_, this_.username as username5_7_0_, this_.account_locked as account_6_7_0_, this_."password" as password7_7_0_, this_.account_expired as account_8_7_0_, this_.enabled as enabled9_7_0_ from user this_ where this_.username=? [42102-196]
2019-11-22 13:57:04 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 13:57:04 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 14:00:06 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 14:00:06 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Tabla "RUBRO" no encontrada
Table "RUBRO" not found; SQL statement:
select this_.id as id1_4_0_, this_.version as version2_4_0_, this_.nombre as nombre3_4_0_, this_.sector_id as sector_i4_4_0_ from rubro this_ [42102-196]
2019-11-22 17:21:47 database: wrong user or password; user: ""
org.h2.message.DbException: Nombre de usuario รณ password incorrecto
Wrong user name or password [28000-196]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at com.intellij.database.remote.jdbc.helpers.JdbcHelperImpl.connect(JdbcHelperImpl.java:590)
	at com.intellij.database.remote.jdbc.impl.RemoteDriverImpl.connect(RemoteDriverImpl.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Nombre de usuario รณ password incorrecto
Wrong user name or password [28000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 31 more
2019-11-22 17:21:51 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1740)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:495)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-11-22 17:22:41 jdbc[3]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1740)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:495)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-11-22 17:22:46 jdbc[4]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1740)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:495)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-11-22 17:22:53 jdbc[5]: exception
java.sql.SQLClientInfoException: Client info name 'ApplicationName' not supported.
	at org.h2.jdbc.JdbcConnection.setClientInfo(JdbcConnection.java:1740)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setClientInfo(RemoteConnectionImpl.java:495)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
